**MOVIE RECOMMENDATIONS USING COLLABORATIVE FILTERING**

*Collaborative Filtering*

Collaborative Filtering, on the other hand, doesn’t need anything else except users’ historical preference on a set of items. Because it’s based on historical data, the core assumption here is that the users who have agreed in the past tend to also agree in the future.

*Advantages*

- No domain knowledge necessary

- We don't need domain knowledge because the embeddings are automatically learned.

- The model can help users discover new interests. In isolation, the ML system may not know the user is interested in a given item, but the model might still recommend it because similar users are interested in that item.

- To some extent, the system needs only the feedback matrix to train a matrix factorization model. In particular, the system doesn't need contextual features. In practice, this can be used as one of multiple candidate generators.


*Concepts used here*

- **Matrix Factorization**

- **Cosine Similarity**

*Types of Approaches Used*

- **Item-Based Collaborative Filtering** 

Suggests an item based on items the user has previously consumed. It looks for the items the user has consumed then it finds other items similar to consumed items and recommends accordingly.

- **User Based Collaborative Filtering**

This approach heavily relies on active user neighborhood information to make predictions and recommendations. Neighborhood selection can either make or break the recommendation for an active user and can have a direct bearing on the rating prediction and item recommendation.


**User - Based Collaborative Filtering**

In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
rate = pd.read_csv(r"C:\Users\USER\OneDrive\Desktop\ratings.csv")
rate.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [19]:
rate.shape

(100836, 4)

In [20]:
movies = pd.read_csv(r"C:\Users\USER\OneDrive\Desktop\movies.csv")
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [21]:
movies['title']

0                                Toy Story (1995)
1                                  Jumanji (1995)
2                         Grumpier Old Men (1995)
3                        Waiting to Exhale (1995)
4              Father of the Bride Part II (1995)
                          ...                    
9737    Black Butler: Book of the Atlantic (2017)
9738                 No Game No Life: Zero (2017)
9739                                 Flint (2017)
9740          Bungo Stray Dogs: Dead Apple (2018)
9741          Andrew Dice Clay: Dice Rules (1991)
Name: title, Length: 9742, dtype: object

**Train-test split**

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test = train_test_split(rate, test_size = 0.3, random_state = 42)
print(x_train.shape)
print(x_test.shape)

(70585, 4)
(30251, 4)


In [23]:
user = x_train.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(0)
user.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  190221  191005  193565  193571  193573  193579  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  193581  193583  193585  193609  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 8566 columns]

**Create a copy of train and test dataset**

In [24]:
traind = x_train.copy()
testd = x_test.copy()
traind['rating'] = traind['rating'].apply(lambda x: 0 if x > 0 else 1)
testd['rating'] = testd['rating'].apply(lambda x: 1 if x > 0 else 0)

In [25]:
traind = traind.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(1)
testd = testd.pivot(index = 'userId', columns = 'movieId', values = 'rating').fillna(0)

In [26]:
traind.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     1.0     0.0     1.0     1.0     0.0     1.0     1.0   
2           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
5           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  9       10      ...  190221  191005  193565  193571  193573  193579  \
userId                   ...                                                   
1           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
2           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
5           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  193581  193583  193585  193609  
userId                                   
1           1.0     1.0     1.0     1.0  
2           1.0     1.0     1.0     1.0  
3           1.0     1.0     1.0     1.0  
4           1.0     1.0     1.0     1.0  
5           1.0     1.0     1.0     1.0  

[5 rows x 8566 columns]

**User - User Similarity Matrix**

Using Cosine Similarity

In [27]:
# User Similarity Matrix using Cosine similarity as a similarity measure between Users
from sklearn.metrics.pairwise import cosine_similarity

sim = cosine_similarity(user)
sim[np.isnan(sim)] = 0
print(sim)
print(sim.shape)

[[1.         0.01799262 0.02914591 ... 0.22586534 0.12184689 0.13241346]
 [0.01799262 1.         0.         ... 0.04299081 0.03472882 0.0625667 ]
 [0.02914591 0.         1.         ... 0.00378273 0.         0.02382229]
 ...
 [0.22586534 0.04299081 0.00378273 ... 1.         0.10982639 0.21962266]
 [0.12184689 0.03472882 0.         ... 0.10982639 1.         0.05416081]
 [0.13241346 0.0625667  0.02382229 ... 0.21962266 0.05416081 1.        ]]
(610, 610)


**Predicting user ratings on the movies**

In [28]:
pred = np.dot(sim, user)
pred

array([[8.52008912e+01, 3.99290227e+01, 2.08165173e+01, ...,
        2.81820351e-02, 2.81820351e-02, 1.57425084e-01],
       [2.45531356e+01, 1.05987273e+01, 2.94172315e+00, ...,
        8.74389309e-02, 8.74389309e-02, 4.49741734e-01],
       [4.22670774e+00, 2.11463396e+00, 9.59320674e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [9.49265311e+01, 4.92867089e+01, 2.12555470e+01, ...,
        2.51644930e-02, 2.51644930e-02, 5.92666313e-01],
       [7.50962548e+01, 3.56578151e+01, 1.17138113e+01, ...,
        0.00000000e+00, 0.00000000e+00, 6.43083908e-02],
       [7.67153155e+01, 3.67625117e+01, 1.11564580e+01, ...,
        2.61466866e-01, 2.61466866e-01, 8.03583319e-01]])

In [29]:
pred.shape

(610, 8566)

We do not want to recommend the same movie that the user already watched. We are interested only in the movies not rated by the user, we will ignore the movies rated by the user.

This is where we will use our dummy train matrix that we previously built.

In [30]:
final = np.multiply(pred,traind)
final.head()

movieId     1          2          3         4          5          6       \
userId                                                                     
1         0.000000  39.929023   0.000000  1.220732  10.483532   0.000000   
2        24.553136  10.598727   2.941723  0.085473   2.773060  10.458197   
3         4.226708   2.114634   0.959321  0.066644   0.308448   2.855740   
4        50.832807  23.786786   9.793001  0.706291   6.609481  24.594138   
5        60.794262  36.875980  12.358414  2.321889  13.215004  29.323176   

movieId     7         8         9          10      ...    190221    191005  \
userId                                             ...                       
1        14.082187  2.605186  4.111435  47.981999  ...  0.083324  0.036234   
2         2.308815  0.523106  0.588578  11.698251  ...  0.054182  0.112421   
3         0.518991  0.105484  0.190006   2.550762  ...  0.008707  0.000000   
4        10.881808  1.505819  2.196956  27.970658  ...  0.005910  0.065396   
5        14.149193  3.043103  2.351687  47.983608  ...  0.108995  0.000000   

movieId    193565    193571    193573    193579    193581    193583    193585  \
userId                                                                          
1        0.028182  0.032208  0.032208  0.028182  0.032208  0.028182  0.028182   
2        0.087439  0.099930  0.099930  0.087439  0.099930  0.087439  0.087439   
3        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4        0.050864  0.058130  0.058130  0.050864  0.058130  0.050864  0.050864   
5        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

movieId    193609  
userId             
1        0.157425  
2        0.449742  
3        0.000000  
4        0.106328  
5        0.103332  

[5 rows x 8566 columns]

In [57]:
print(final.iloc[35].sort_values(ascending = False)[0:5])

movieId
296     43.029288
356     41.969139
2571    34.761966
593     34.017476
260     31.397504
Name: 36, dtype: float64


**Item-based collaborative filtering**

In [32]:
features = x_train.pivot(index = 'movieId', columns = 'userId',values = 'rating').fillna(0)
features.head()

userId   1    2    3    4    5    6    7    8    9    10   ...  601  602  603  \
movieId                                                    ...                  
1        4.0  0.0  0.0  0.0  0.0  0.0  4.5  0.0  0.0  0.0  ...  0.0  0.0  4.0   
2        0.0  0.0  0.0  0.0  0.0  4.0  0.0  4.0  0.0  0.0  ...  0.0  4.0  0.0   
3        4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4        0.0  0.0  0.0  0.0  0.0  3.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5        0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

userId   604  605  606  607  608  609  610  
movieId                                     
1        0.0  4.0  2.5  0.0  2.5  3.0  5.0  
2        0.0  3.5  0.0  0.0  0.0  0.0  0.0  
3        0.0  0.0  0.0  0.0  2.0  0.0  0.0  
4        0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5        3.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 610 columns]

**Item-item similarity matrix**

Using cosine similarity

In [33]:
from sklearn.metrics.pairwise import cosine_similarity

item_sim = cosine_similarity(features)
print(item_sim)

[[1.         0.3250275  0.20868811 ... 0.         0.         0.        ]
 [0.3250275  1.         0.16373912 ... 0.         0.         0.        ]
 [0.20868811 0.16373912 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         1.         0.        ]
 [0.         0.         0.         ... 1.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [34]:
#!D mqtrix multiplication

item_pred = np.dot(features.T, item_sim)
item_pred

array([[1.70457674e+02, 1.45736065e+02, 1.43879168e+02, ...,
        4.90965204e-01, 4.90965204e-01, 2.29232951e+00],
       [1.47046553e+01, 1.27977597e+01, 7.41114463e+00, ...,
        4.11059622e-01, 4.11059622e-01, 2.92895445e+00],
       [4.64495934e+00, 3.92745275e+00, 3.15259091e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [3.43701501e+02, 3.24195971e+02, 2.65563257e+02, ...,
        1.03906576e+00, 1.03906576e+00, 1.84582165e+01],
       [2.59031967e+01, 2.12250531e+01, 1.32545528e+01, ...,
        0.00000000e+00, 0.00000000e+00, 3.54245954e-01],
       [5.33648012e+02, 4.18264714e+02, 2.11408804e+02, ...,
        1.91118832e+01, 1.91118832e+01, 3.78219746e+01]])

**Not rated by the user**

In [35]:
item_final_ratings = np.multiply(item_pred, traind)
item_final_ratings.head()

movieId     1           2          3          4          5          6       \
userId                                                                       
1         0.000000  145.736065   0.000000  17.752252  60.018339   0.000000   
2        14.704655   12.797760   7.411145   0.269430   5.804070  10.243947   
3         4.644959    3.927453   3.152591   0.227362   0.903036   4.159893   
4        82.099482   70.871325  49.487513  10.082054  34.732576  65.274992   
5        29.845750   30.143357  18.279888   9.367018  17.505036  23.594082   

movieId     7          8          9           10      ...    190221    191005  \
userId                                                ...                       
1        64.555580  56.220407  28.999703  143.817617  ...  1.537469  0.490965   
2         3.230076   4.735767   1.599833   10.960730  ...  0.461311  0.411060   
3         1.724414   0.864785   1.312176    4.381157  ...  0.047166  0.000000   
4        41.705394  29.677329  12.913699   70.165084  ...  0.069251  0.629317   
5        17.286535  13.692940   5.029116   31.156561  ...  0.694836  0.000000   

movieId    193565    193571    193573    193579    193581    193583    193585  \
userId                                                                          
1        0.490965  0.490965  0.490965  0.490965  0.490965  0.490965  0.490965   
2        0.411060  0.411060  0.411060  0.411060  0.411060  0.411060  0.411060   
3        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
4        0.629317  0.629317  0.629317  0.629317  0.629317  0.629317  0.629317   
5        0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

movieId    193609  
userId             
1        2.292330  
2        2.928954  
3        0.000000  
4        1.033695  
5        0.537539  

[5 rows x 8566 columns]

In [54]:
item_final_ratings.iloc[7].sort_values(ascending = False)[0:5] 

movieId
592    40.812195
356    38.969016
588    38.206123
316    37.130888
500    37.005250
Name: 8, dtype: float64

**Evaluation**

**Using user- user evaluation**

Going for already rated ones

In [37]:
test_user = x_test.pivot(index = 'userId', columns = 'movieId',values = 'rating').fillna(0)

test_user_sim = cosine_similarity(test_user)
test_user_sim[np.isnan(test_user_sim)] = 0

print(test_user_sim)
print(test_user_sim.shape)

[[1.         0.         0.07126637 ... 0.0749648  0.         0.02105064]
 [0.         1.         0.         ... 0.02631254 0.         0.04691426]
 [0.07126637 0.         1.         ... 0.         0.         0.        ]
 ...
 [0.0749648  0.02631254 0.         ... 1.         0.06079015 0.12466251]
 [0.         0.         0.         ... 0.06079015 1.         0.02233952]
 [0.02105064 0.04691426 0.         ... 0.12466251 0.02233952 1.        ]]
(610, 610)


In [38]:
user_pred_test  = np.dot(test_user_sim,test_user)
user_pred_test

array([[ 8.01521825,  3.22701218,  1.71422693, ...,  0.04154912,
         0.        ,  0.        ],
       [ 1.64920152,  0.91304857,  0.02113666, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.07587801,  0.07241296,  0.1867716 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [17.86102484, 10.1363879 ,  4.48304633, ...,  0.0274908 ,
         0.        ,  0.        ],
       [ 3.10351661,  2.6934212 ,  1.20357903, ...,  0.        ,
         0.        ,  0.        ],
       [12.36110509,  5.79632466,  1.96280959, ...,  0.        ,
         0.20526264,  0.23947308]])

In [39]:
test_user_final_rating = np.multiply(user_pred_test, testd)
test_user_final_rating.head()

movieId     1       2       3       4       5       6       7       8       \
userId                                                                       
1         0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2         0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3         0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4         0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5        28.077679     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  187595  189043  189111  189333  189547  189713  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  190213  190219  193567  193587  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 6124 columns]

In [40]:
rate['rating'].describe()

count    100836.000000
mean          3.501557
std           1.042529
min           0.500000
25%           3.000000
50%           3.500000
75%           4.000000
max           5.000000
Name: rating, dtype: float64

In [41]:
from sklearn.preprocessing import MinMaxScaler

X = test_user_final_rating.copy() 
X = X[X > 0] # only consider non-zero values as 0 means the user haven't rated the movies

scaler = MinMaxScaler(feature_range = (0.5, 5))
scaler.fit(X)
pred = scaler.transform(X)

print(pred)

[[       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 ...
 [       nan 2.28631493        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]]


In [42]:
test = x_test.pivot(index = 'userId', columns = 'movieId', values = 'rating')
test.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10      ...  187595  189043  189111  189333  189547  189713  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  190213  190219  193567  193587  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  

[5 rows x 6124 columns]

In [43]:
# total non-NaN value
total_non_nan = np.count_nonzero(~np.isnan(pred))
total_non_nan

30251

In [44]:
diff_sqr_matrix = (test - pred)**2
sum_of_squares_err = diff_sqr_matrix.sum().sum() # df.sum().sum() by default ignores null values

rmse = np.sqrt(sum_of_squares_err/total_non_nan)
print(rmse)

1.5633169894889727


In [45]:
mae = np.abs(pred - test).sum().sum()/total_non_nan
print(mae)

1.2090888492640433


**Using item - item similarity**

In [46]:
test_item_features = x_test.pivot(index = 'movieId', columns = 'userId', values = 'rating').fillna(0)
test_item_similarity = cosine_similarity(test_item_features)
test_item_similarity[np.isnan(test_item_similarity)] = 0 

print(test_item_similarity)
print("- "*10)
print(test_item_similarity.shape)

[[1.         0.15732306 0.09932171 ... 0.         0.         0.        ]
 [0.15732306 1.         0.         ... 0.         0.         0.        ]
 [0.09932171 0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         1.        ]
 [0.         0.         0.         ... 0.         1.         1.        ]]
- - - - - - - - - - 
(6124, 6124)


In [47]:

item_predicted_ratings_test = np.dot(test_item_features.T, test_item_similarity )
item_predicted_ratings_test

array([[1.90435509e+01, 1.37292388e+01, 1.20305765e+01, ...,
        4.19602222e-01, 0.00000000e+00, 0.00000000e+00],
       [9.33282962e-01, 1.09150271e+00, 6.76481425e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.34037111e+00, 3.35148768e-01, 5.76138709e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [6.10452867e+01, 6.86734298e+01, 3.74823847e+01, ...,
        4.19602222e-01, 0.00000000e+00, 0.00000000e+00],
       [1.59448344e+00, 1.48111314e+00, 1.51270481e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.50933268e+01, 5.62696921e+01, 2.60485764e+01, ...,
        0.00000000e+00, 8.98355095e+00, 8.98355095e+00]])

**Testing on the movies already rated by the user**

In [48]:
test_item_final_rating = np.multiply(item_predicted_ratings_test, testd)
test_item_final_rating.head()

movieId    1       2       3       4       5       6       7       8       \
userId                                                                      
1        0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2        0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3        0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4        0.000000     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5        9.480468     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  187595  189043  189111  189333  189547  189713  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  190213  190219  193567  193587  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 6124 columns]

In [49]:

rate['rating'].describe()

count    100836.000000
mean          3.501557
std           1.042529
min           0.500000
25%           3.000000
50%           3.500000
75%           4.000000
max           5.000000
Name: rating, dtype: float64

In [50]:
from sklearn.preprocessing import MinMaxScaler

X = test_item_final_rating.copy() 
X = X[X > 0] # only consider non-zero values as 0 means the user haven't rated the movies

scaler = MinMaxScaler(feature_range = (0.5, 5))
scaler.fit(X)
pred = scaler.transform(X)

print(pred)

[[       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 ...
 [       nan 2.06051833        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]
 [       nan        nan        nan ...        nan        nan        nan]]


In [51]:
total_non_nan = np.count_nonzero(~np.isnan(pred))
total_non_nan

30251

In [52]:
test = x_test.pivot(index = 'userId', columns = 'movieId', values = 'rating')
test.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  9       10      ...  187595  189043  189111  189333  189547  189713  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  190213  190219  193567  193587  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  

[5 rows x 6124 columns]

In [53]:
#RMSE sscore

diff_item_matrix = (test - pred)**2
sserr = diff_item_matrix.sum().sum()

rmse = np.sqrt(sserr/total_non_nan)
print(rmse)

2.512699212653213


**User-based collaborative filtering performs more efficiently item-based collaborative filtering.**